import { GetStaticProps, InferGetStaticPropsType, type NextPage } from "next";
import Head from "next/head";
import Layout from "../components/layout";
import Link from "next/link";
import { Product } from "types";
import Image from "next/image";
import ProductCard from "components/product-list";
const Home: NextPage = ({
  products,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  console.log("Products es", products);
  const productList = products?.products;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="grid grid-cols-12">
          {productList.map((product: Product) => (
            <ProductCard product={product} key={product.id} />
          ))}
        </div>
      </Layout>
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const response = await fetch("https://dummyjson.com/products");
  const data = await response.json();
  return {
    props: {
      products: data as Product[],
    },
  };
};
export default Home;
