import { GetStaticProps, InferGetStaticPropsType, type NextPage } from "next";
import Head from "next/head";
import Layout from "../components/layout";
import Link from "next/link";
import { Product } from "types";
import Image from "next/image";
import ProductCard from "components/product-list";
import { useFilter } from "hooks/useFilter";
import { Toaster } from "react-hot-toast";
const Home: NextPage = ({
  products,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  console.log("Products es", products);
  const productList = products?.products;
  const filteredProducts = useFilter(productList);
  return (
    <>
      <Head>
        <title>Fake Ecommerce with React/Next.js</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="-mx-px grid grid-cols-2 border-l border-gray-200 sm:mx-0 md:grid-cols-3 lg:grid-cols-4">
          {filteredProducts.length > 0 ? (
            filteredProducts.map((product: Product) => (
              <ProductCard product={product} key={product.id} />
            ))
          ) : (
            <div>No hay resultados para tu busqueda</div>
          )}
        </div>
      </Layout>
      <Toaster />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const response = await fetch("https://dummyjson.com/products");
  const data = await response.json();
  return {
    props: {
      products: data as Product[],
    },
  };
};
export default Home;
